ios/AvoidSoftInput.swift
ios/AvoidSoftInputView.swift

When soft input is quickly closed or opened, animations were not interrupted,
so it could end up with some blank area under content left, or content could have been cut
That commit resolves issue by adding .beginCurrentState option to UIView.animate method and
by adding some additional checks whether view is being translated up or down

fix(#10): not cancelled animations on iOS

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputProvider.kt
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputUtils.kt

So far, when calculating keyboard height and applied offset on Android,
navigation bar value was subtracted, even if navigation bar is separate from
screen, like in Nexus S device
This commit, calculates bottom inset based on WindowInsets API (and falls back
to View.getWindowVisibleDisplayFrame on Android API < 23) - that way,
if navigation bar is separate from screen, its height will not be subtracted
when calculating keyboard height and bottom inset.
Closes #37

fix(#37): incorrect keyboard height returned on nexus_s device

---

packages/mobile/ios/Podfile.lock
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt
packages/react-native-avoid-softinput/ios/AvoidSoftinput.xcodeproj/project.pbxproj

This pull request resolves #47 
There was a different behavior when applied padding had to be removed from
scroll view after user used only soft keyboard or typed sth with physical
keyboard on Android.
When physical keyboard was used, either by submitting with Enter key,
or just by typing some character, scrollview which had applied padding
couldn't be find inside AvoidSoftInputManager.kt
Solution:
As it is done for rootview, reference to scrollview that has applied
padding, is saved. When manager cannot find scrollview by traversing
rootview, it looks to saved reference.
- [] iOS
Try to submit input with physical keyboard

fix(#47): [Android] Not hidden space in scrollview after keyboard dismissal

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputUtils.kt

This pull request resolves #52 
When user dismissed screen with focused input and visible keyboard,
internal values in AvoidSoftInputManager were not reset, because
focused view was already destroyed
Solution:
When there is event with final keyboard height value equal 0 and
mSoftInputVisible is still `true`, and focused view is null,
there will be early return, so just reset values to default ones
- [] iOS
- Open FormExample in example app. 
- Tap input
- Press back button inside header
- Revisit FormExample and tap input
- It shouldn't cover whole screen with padding, as it was in linked issue

fix(#52): not reset internal values on Android

---

packages/app/src/navigation/index.tsx
packages/react-native-avoid-softinput/ios/AvoidSoftInputManager.swift

This pull request resolves #54 
When user tried to swipe-to-dismiss screen on iOS, but finally aborted it, offset was incorrectly reapplied.
This PR checks if offset was actually removed when user screen swipes.
Open example app on iOS and try to screen swipe when text input is focused

fix(#54): incorrect offset when screen swiping on iOS

---

packages/mobile/ios/Podfile.lock
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt

This pull request resolves #81 
move `View.OnScrollChangeListener` listener to `setScrollListener` method (inside if API >= 23 condition)
Run on simulator/device with Android API < 23

fix(#81): crashes with API < 23 & View.OnScrollChangeListener

---

docs/docs/guides/INSTALLATION.mdx

This pull request resolves #88 
Add a troubleshooting section on the documentation to tackle building Android with this library

docs(#88): add troubleshooting section

---

packages/react-native-avoid-softinput/android/gradle.properties
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt

This pull request resolves #90 
fix 'onAnimationEnd' overrides nothing(compileSdkVersion>=33) - Type mismatch: inferred type is Animator? but Animator was expected
Run example app with compileSdkVersion and targetSdkVersion set to 33

fix(#90): 'onAnimationEnd' overrides nothing(compileSdkVersion>=33)

---

docs/docs/recipes/STICKY_FOOTER.mdx
docs/versioned_docs/version-2.0.x/recipes/STICKY_FOOTER.mdx
docs/versioned_docs/version-3.0.x/recipes/STICKY_FOOTER.mdx

This pull request resolves #125 
remove not necessary `setEnabled(true)` in sticky footer docs

fix(#125): not necessary `setEnabled(true)` in sticky footer docs

---

packages/react-native-avoid-softinput/react-native-avoid-softinput.podspec

This pull request resolves #124 
- remove folly version not needed in Fabric from RN 0.70

refactor(#124): folly version not needed in Fabric from RN 0.70

---

packages/react-native-avoid-softinput/ios/AvoidSoftInputObjCPPUtils.mm

This pull request resolves (#131)
Added a condition to check whether the subviews array is empty or not. It fixes application crashes in case the subviews array comes empty.

fix(#131): fix native crash when the subviews array is empty

---

packages/react-native-avoid-softinput/package.json

This pull request resolves #141 
After renaming podspec file, it wasn't updated in package.json files field, so there's no podspec in 3.1.0 in NPM

fix(#141): missing podspec in NPM package

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/animations/AnimationHandlerImpl.kt

This pull request resolves #144 
Move code in `runAnimator` method to run on UI thread
Run one of examples and try to quickly cancel the animation (show and quickly hide the keyboard)

fix(#144): animation crash on Android

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/animations/AnimationHandlerImpl.kt

This pull request resolves scrollview will scroll to 0 sometimes in android
when function `onfocus()` called, the `mSoftInputVisible` sometimes will be false, so the `mScrollY` can't be updated when onFocus. Then  if user don't scroll the content(no ScrollListener callback, no `mScrollY` update), instead, he collapse keyboard immediately, in `removeOffsetInScrollView()` method, scrollview will scroll to 0(because `mScrollY` now is 0).

fix: android scrollview will scroll to 0 when unfocused

---

packages/react-native-avoid-softinput/src/index.tsx

This pull request resolves #168 
**Auto import issue #168**
-  Android
-  iOS

fix: auto import components

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/animations/AnimationHandlerImpl.kt

This pull request resolves #175 
Because of passing wrong view to the `getScrollToOffset` measurement util (scrollview instead of currenly focused input), the scrollview was being scrolled even when the input was not being covered by the keyboard.

fix(#175): unnecessary scroll even when it's not needed

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/animations/AnimationHandlerImpl.kt

This pull request resolves #192 
fix unnecessary offset for root view on Android
I have no clue why that code was even included here

fix(#192): unnecessary offset for root view on Android

---

packages/react-native-avoid-softinput/android/build.gradle

This pull request resolves an issue when building on Android with the "New Architecture" enabled for React Native 0.75.
I recently updated all of my apps to React Native 0.75 and I tried to enable the "New Architecture" on most of them. One of these apps uses the `react-native-avoid-softinput` package which did not build properly on Android. 
I tried to dig through the issue and found out that it failed while trying to find a non-existent `resolveReactNativeDirectory()` function in `project.ext`. I'm pretty sure this worked as expected in previous version of React Native with the "New Architecture" enabled, but most probably stopped working since they made some internal reorganization or something similar.
The fix is fairly straight-forward - I checked what most of the …

fix: make Android new arch build work RN 0.75

---

packages/react-native-avoid-softinput/package.json
packages/react-native-avoid-softinput/src/AvoidSoftInput.ts
yarn.lock

This PR brings `react-native-edge-to-edge` detection to `react-native-avoid-softinput`.
The future of Android is [edge-to-edge](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge), and to make the React Native developer experience seamless in this regard, the ecosystem needs to transition from “opaque system bars by default” to “edge-to-edge by default.”
To prevent library authors from implementing their own edge-to-edge solutions—which could interfere with other libraries—and because it’s not possible to reliably detect if edge-to-edge is already enabled on Android, we have collaborated with [Expo](https://expo.dev/) to create a library that handles this functionality and is detectable using a simple helper: …

Detect react-native-edge-to-edge and bypass setShouldMimicIOSBehavior

---

packages/react-native-avoid-softinput/ios/AvoidSoftInputListener.mm

This pull request resolves #226 

fix(#226): incorrect height reported when UIAccessibilityPrefersCrossFadeTransitions is enabled

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputPackage.kt
packages/react-native-avoid-softinput/android/src/newarch/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewManager.kt
packages/react-native-avoid-softinput/android/src/oldarch/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewManager.kt
packages/react-native-avoid-softinput/ios/AvoidSoftInputViewComponentView.mm
packages/react-native-avoid-softinput/package.json
yarn.lock

fix: incompatibilities or deprecations with new architecture code

---

packages/react-native-avoid-softinput/package.json

Fixes problem with npm not supporting "workspace:" URL when running `npm version` in release workflow

chore: fix broken npm version when releasing library

---

packages/react-native-avoid-softinput/ios/AvoidSoftInputManager.mm

This pull request resolves #241 
The root cause of the issue were multiple keyboard notifications being sent over up to 30ms.
The solution is to debounce animation call by 3 frames (48ms) and use the target height from the latest notification.

fix(#241): password fields on iOS having doubled offset applied

---

packages/react-native-avoid-softinput/android/src/oldarch/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewManager.kt

Build fails with the old architecture in RN 0.80
```
e: node_modules/react-native-avoid-softinput/android/src/reactnative77/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewDelegate.kt:16:76 Argument type mismatch: actual type is 'String?', but 'String' was expected.
e: node_modules/react-native-avoid-softinput/android/src/reactnative77/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewDelegate.kt:18:30 Unresolved reference 'setEnabled'.
```

fix(oldarch): setIsEnabled -> setEnabled
