mateusz1913/react-native-avoid-softinput

android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputModule.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputUtils.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputView.kt

fix(#3): soft input height being pixel value on android

---

README.md
example/src/screens/BottomScrollViewWithFlex.tsx
example/src/screens/FullScreenView.tsx
src/hooks.ts
src/index.tsx
src/stateReducer.ts

feat(#4): custom hooks

---

example/ios/Podfile.lock
ios/AvoidSoftInput.swift
ios/AvoidSoftInputView.swift

fix(#8): events not always emitted on iOS

---

android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputModule.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputView.kt

The same issue as #10 but on Android
Closes #12

fix(#12): not cancellable animations on Android

---

ios/AvoidSoftInput.swift
ios/AvoidSoftInputUtils.swift
ios/AvoidSoftInputView.swift
react-native-avoid-softinput.podspec

fix(#14): tvOS compiling errors

---

android/build.gradle
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputInterpolator.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputModule.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputView.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewManager.kt
example/src/screens/AppliedOffsetEvents.tsx
example/src/screens/FullScreenScrollView.tsx
ios/AvoidSoftInput.m
ios/AvoidSoftInput.swift
ios/AvoidSoftInputProtocol.swift
ios/AvoidSoftInputView.swift
ios/AvoidSoftInputViewManager.m
src/AvoidSoftInputModule.tsx
src/AvoidSoftInputView.tsx
src/types.ts

Closes #17 
- `setEasing` method for module
- `easing` prop for native component
Available values are `easeIn`, `easeInOut`, `easeOut`, `linear`
Default value is `linear`

feat(#17): easing type for offset animation

---

android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInput.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputModule.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputUtils.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputView.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewManager.kt
example/android/app/src/main/java/com/example/reactnativeavoidsoftinput/MainActivity.java
example/src/screens/CustomAnimationConfigWithComponent.tsx
example/src/screens/CustomAnimationConfigWithModule.tsx
example/src/screens/Examples.ts
example/src/screens/ModalView.tsx
ios/AvoidSoftInput.m
ios/AvoidSoftInput.swift
ios/AvoidSoftInputProtocol.swift
ios/AvoidSoftInputUtils.swift
ios/AvoidSoftInputView.swift
ios/AvoidSoftInputViewManager.m
src/AvoidSoftInputModule.tsx
src/AvoidSoftInputView.tsx

Closes #18
- duration & delay set methods for "global" module
- duration & delay props for native component
- refactor for computeSoftInputOffset methods
- new examples

feat(#18): duration & delay offset animation config

---

ios/AvoidSoftInputUtils.swift

fix(#23): ios scroll insets not preserved when offset is applied

---

example/ios/Podfile.lock
example/package.json
example/src/hooks/useSoftInputHandler.ts
example/src/navigation/routes.ts
example/src/navigation/screens.ts
example/src/navigation/types.ts
example/src/screens/AppliedOffsetEvents.tsx
example/yarn.lock

Because of bugs in reanimated beta v2.3, Android example has been unresponsive
when navigating back to home screen, iOS example has been unresponsive
when dismissing RN modal
Solution: for now reverted to reanimated v2.2 and commented out AppliedOffsetEvents example
(it's using APIs available from v2.3)

fix: example bugs

---

android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputModule.kt
android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputUtils.kt
ios/AvoidSoftInput.swift
ios/AvoidSoftInputUtils.swift
ios/AvoidSoftinput-Bridging-Header.h

fix(#28): dark area between bottom edge of rootview and soft input

---

.github/PULL_REQUEST_TEMPLATE.md

This pull request resolves ???
- [] Android
- [] iOS

chore: checkboxes in pull request template

---

packages/react-native-avoid-softinput/ios/AvoidSoftInputManager.swift

This pull request resolves #54 
This pull request resolves #59 
Fix incorrect offsets when user tries to screen swipe

fix(#54, #59): screen swipe incorrect offsets

---

packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt

fix mateusz1913/react-native-avoid-softinput#63

fix: cast exception android  

---

packages/mobile/ios/Podfile
packages/mobile/ios/Podfile.lock

This pull request resolves #61 
Add touch indicator in example iOS app
Open iOS example app and try to tap somewhere

feat: `pod 'ShowTime'` - visual touch indicator on iOS

---

.github/ISSUE_TEMPLATE/example_app_bug_report.yml

This pull request resolves #69 
improve bug templates

chore(#69): improve bug templates

---

CONTRIBUTING.md

This pull request resolves #71 
improve contributions guide

chore(#71): improve contributions guide [skip ci]

---

docs/docs/api/view/VIEW.mdx
docs/docs/guides/USAGE_VIEW.mdx
docs/docs/recipes/ANIMATIONS.mdx
docs/docs/recipes/BOTTOM_SHEET.mdx
docs/docs/recipes/CUSTOM_CONFIG.mdx
docs/docs/recipes/FORM.mdx
docs/docs/recipes/MODAL.mdx
docs/docs/recipes/STICKY_FOOTER.mdx
packages/app/src/navigation/index.tsx
packages/app/src/navigation/routes.ts
packages/app/src/navigation/types.ts
packages/app/src/screens/EnabledViewPropExample.tsx
packages/app/src/screens/HomeScreen.tsx
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputManager.kt
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputView.kt
packages/react-native-avoid-softinput/android/src/main/java/com/reactnativeavoidsoftinput/AvoidSoftInputViewManager.kt
packages/react-native-avoid-softinput/ios/AvoidSoftInputManager.swift
packages/react-native-avoid-softinput/ios/AvoidSoftInputView.swift
packages/react-native-avoid-softinput/ios/AvoidSoftInputViewManager.m
packages/react-native-avoid-softinput/src/types.ts

This pull request resolves #50 
`enabled` prop for `AvoidSoftInputView`
New example `EnabledViewPropExample`

feat(#50): `enabled` prop for `AvoidSoftInputView`

---

.github/workflows/build-docs.yml

Skip when there are no changes to docs, library's source code or
build-docs workflow

chore: skip build-docs workflow when there are no changes

---

packages/app/package.json

- specify peer dependencies to fix github actions during npm release pipeline:
ERROR npm WARN ERESOLVE overriding peer dependency

chore: specify peer dependencies versions to fix github actions error

---

.github/workflows/lint-android.yml
.github/workflows/lint-ios.yml
.github/workflows/lint-js.yml
.husky/commit-msg
.husky/pre-commit
CONTRIBUTING.md
lefthook.yml
package.json
yarn.lock

This pull request resolves #93 
- replace husky with lefthook
- add lint github workflows

chore(#93): replace husky with lefthook, add lint github workflows

---

packages/react-native-avoid-softinput/jest/mock.js
packages/react-native-avoid-softinput/package.json
tsconfig.build.json

This pull request resolves #101 
add jest mock; docs section will be handled in #103 

feat(#101): jest mock

---

packages/fabricMobile/package.json
yarn.lock

fix: unsupported link: URL - link: is supported only with yarn - change it to file:

fix: unsupported link: url

---

.github/workflows/lint-android.yml
.github/workflows/lint-ios.yml
lefthook.yml

This pull request resolves #106 
fixed lint-ios github workflow
split lint-ios git hook into lint-swift and lint-objc and fix change files pattern

chore(#106): improve lint-ios

---

packages/app/src/navigation/index.tsx
packages/app/src/navigation/routes.ts
packages/app/src/navigation/types.ts
packages/app/src/screens/HomeScreen.tsx
packages/app/src/screens/ModalFormSheetExample.tsx
packages/app/src/screens/ScreensNativeModalExample.tsx
packages/mobile/ios/AvoidSoftinputExample.xcodeproj/project.pbxproj
packages/react-native-avoid-softinput/ios/AvoidSoftInputManager.swift

This pull request resolves #86 
Run new ScreensNativeModalExample and try to interactively dismiss modal with keyboard displayed

fix(#86): applied offset being rarely removed from incorrect root view

---

README.md
packages/react-native-avoid-softinput/README.md

This pull request provides information about usage of this library in Expo projects. The message is copied from Expo's standard content for READMEs: https://expo.notion.site/Documenting-Expo-support-in-READMEs-f250a20b4bd5472cab0757918cb21062#ae1f2e4734b34fe3be292f777591517b
None

chore: update readme to include information about Expo installation

---

.github/workflows/build-docs.yml
.github/workflows/lint-android.yml
.github/workflows/lint-ios.yml
.github/workflows/lint-js.yml
.github/workflows/npm-release-template.yml

Upgrade from v2 to v3:
- actions/checkout
- actions/cache
- actions/setup-node

chore: upgrade github actions

---

packages/app/src/navigation/index.tsx
packages/app/src/navigation/routes.ts
packages/app/src/navigation/types.ts
packages/app/src/screens/HomeScreen.tsx
packages/app/src/screens/PasswordFormExample.tsx
packages/react-native-avoid-softinput/ios/AvoidSoftInputAnimationHandler.swift

This pull request resolves #149 
Fixes offset not removed when interacting with iOS password inputs

fix(#149): offset not removed when interacting with iOS password inputs

---

docs/versioned_docs/version-3.0.x/api/view/VIEW.mdx

Just quick fix for an example. So everyone can copy paste this code without a problem

fix(docs): fix import AvoidSoftInputView

---

packages/react-native-avoid-softinput/android/build.gradle

This pull request resolves #170 
Add namespace property to library's build.gradle

feat(#170): add namespace property to build.gradle

---

packages/expo-example/app.json
packages/expo-example/src/consts/colors.ts
packages/expo-example/src/navigation/index.tsx
packages/expo-example/src/navigation/routes.ts
packages/expo-example/src/navigation/types.ts
packages/expo-example/src/screens/HomeScreen.tsx
packages/expo-example/src/screens/LongTextExample.tsx

https://github.com/user-attachments/assets/9674948d-f9df-4084-8f3f-ed235e8e4c1b

chore(#235): long text example with zero animation
